name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore ./src/Ogmios.Domain/Ogmios.Domain.csproj
          dotnet restore ./src/Ogmios.Schema/Ogmios.Schema.csproj
          dotnet restore ./src/Ogmios.Services/Ogmios.Services.csproj

      - name: Build the projects
        run: |
          dotnet build ./src/Ogmios.Domain/Ogmios.Domain.csproj --configuration Release --no-restore
          dotnet build ./src/Ogmios.Schema/Ogmios.Schema.csproj --configuration Release --no-restore
          dotnet build ./src/Ogmios.Services/Ogmios.Services.csproj --configuration Release --no-restore

      - name: Pack Ogmios.Domain
        run: dotnet pack ./src/Ogmios.Domain/Ogmios.Domain.csproj --configuration Release --no-build --no-restore --output ./nupkg

      - name: Pack Ogmios.Services
        run: dotnet pack ./src/Ogmios.Services/Ogmios.Services.csproj --configuration Release --no-build --no-restore --output ./nupkg

      - name: Pack Ogmios.Schema
        run: dotnet pack ./src/Ogmios.Schema/Ogmios.Schema.csproj --configuration Release --no-build --no-restore --output ./nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
